#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	sudo configureUsers "$1" "$2"
else
	#Add a new user with the passed in details
	useradd "$1" -s /bin/bash
	#Set the users password
	echo -e "$2\n$2" | passwd "$1"
	#Add the user to the sudo group
    adduser "$1" sudo
fi
